---
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
        stages: [manual, push]
  - repo: 'https://github.com/ansible-community/ansible-lint.git'
    rev: v24.2.0
    hooks:
      - id: ansible-lint
        pass_filenames: false
        always_run: true
        entry: "ansible-lint"
        args:
          - "--profile=production"
          - "-c=.ansible-lint.yml"
        additional_dependencies:
          - "ansible-core>=2.14"
          - "yamllint>=1.29,<2.0"
...
